version: '3.8'

services:
  customer-tracker:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_KEY=${REACT_APP_SUPABASE_KEY}
    restart: unless-stopped
    container_name: customer-tracker-app 