services:
  customer-tracker:
    build:
      context: .
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_KEY=${REACT_APP_SUPABASE_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: customer-tracker-app
    networks:
      - default
      - dokploy

networks:
  dokploy:
    external: true 