services:
  customer-tracker:
    build:
      context: .
      dockerfile: Dockerfile.debug
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_KEY=${REACT_APP_SUPABASE_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: customer-tracker-debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 