services:
  customer-tracker:
    build:
      context: .
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_KEY=${REACT_APP_SUPABASE_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: customer-tracker-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customer-tracker.rule=Host(`mtm.nebulm.com`)"
      - "traefik.http.routers.customer-tracker.entrypoints=web"
      - "traefik.http.services.customer-tracker.loadbalancer.server.port=80" 